export const VERIFICATION_WORKFLOW = [
  { id: 'A', text: 'Environment Setup', details: 'Python 3.8+, venv, sqlite3, json, re available. ~/.amp-toolboxes exists.' },
  { id: 'B', text: 'Configuration Files', details: '~/.config/amp/settings.json permissions correct.' },
  { id: 'C', text: 'Shell Profile', details: 'AMP_TOOLBOX exported in shell profile.' },
  { id: 'D', text: 'Script Development', details: 'sqlite-query-tool.py has valid syntax and is executable.' },
  { id: 'E', text: 'Test Database', details: 'test.db exists with customer/order tables and ~20 rows.' },
  { id: 'F', text: 'Describe Mode', details: 'TOOLBOX_ACTION=describe returns correct metadata.' },
  { id: 'F.5', text: 'Schema Introspection', details: 'describe_schema method returns table/column metadata.' },
  { id: 'G', text: 'JSON-RPC Parsing', details: 'Valid JSON input returns valid JSON-RPC response.' },
  { id: 'H', text: 'Query Validation', details: 'Non-SELECT queries are rejected with error -32602.' },
  { id: 'I', text: 'Database Execution', details: 'Valid SELECT query returns expected results.' },
  { id: 'J', text: 'Error Handling', details: 'Invalid DB path, malformed JSON return proper errors.' },
  { id: 'K', text: 'Batch Requests', details: 'JSON array input returns a JSON array response.' },
  { id: 'L', text: 'CLI Fallback', details: 'CLI mode with --rpc flag matches execute mode output.' },
  { id: 'M', text: 'Result Limiting', details: 'Results >100 rows are truncated, row_count is correct.' },
  { id: 'N', text: 'Performance', details: 'Typical queries execute in under 1 second.' },
  { id: 'O', text: 'Amp Discovery', details: 'Toolbox is listed correctly in Amp after restart.' },
  { id: 'P', text: 'Amp Execution', details: 'NL -> describe_schema -> SQL -> JSON-RPC works.' },
  { id: 'Q', text: 'Complex Queries', details: 'JOIN queries function correctly.' },
  { id: 'R', text: 'Security Checks', details: 'DROP/UPDATE attempts are rejected.' },
  { id: 'S', text: 'Logging and Debug', details: 'Amp debug logs show correct payloads/responses.' },
  { id: 'T-Z', text: 'Cleanup and Documentation', details: 'README updated, test files removed.' },
];
